### ISSUE TITLE
Unknown Plugin: "module:@babel/plugin-transform-modules-commonjs"

### ISSUE THREAD

**Issue by Cypressxyx** [3846masa/axios-cookiejar-support#162]
looking at the .babel.rc file in axios-cookie-jar-support directory, plugins is defined as:
`{
     "plugins": [ 
         "module:@babel/plugin-transform-modules-commonjs", [ .....
}`

Looking at the babel/plugin-transform-modules-commonjs documentation page,(https://babeljs.io/docs/en/next/babel-plugin-transform-modules-commonjs)

It states that plugin-transform-modules-commonjs (without options) should be loaded as 
`   "plugins": ["@babel/plugin-transform-modules-commonjs"]
}`

Upon removing the "module: "portion in the .babel.rc file found in axios-cookiejar-support, the code compiles again. Is this a possible error or am I not declaring something on my machine that will also note plugin-transform-modules-commonjs as a module?

**Comment by 3846masa** [comment]
Thanks for your report.

Babel docs says, `Any identifier prefixed with module: will have the prefix removed but otherwise be untouched.`
I think your babel version is old OR babel has a bug, please check it.

See https://github.com/babel/website/blob/ec7a872a3ea47e2c084e8e1b5c945faf7a6c4e65/docs/options.md#name-normalization
