### ISSUE TITLE
v 0.5.0 not working with axios 0.19.0 and Node v10.13.0

### ISSUE THREAD

**Issue by akirilyuk** [3846masa/axios-cookiejar-support#189]
Hi,

I cannot use tough cookie jar support v 0.5.0 with axios 0.19.0. on Noe.js v10.13.0

I have tried the example you have in the README.md but it is not working for me:

```js
const axios = require('axios').default;

const axiosCookieJarSupport = require('axios-cookiejar-support').default;
const tough = require('tough-cookie');

const instance = axios.create({
  // WARNING: This value will be ignored.
  jar: new tough.CookieJar(),
});

// Set directly after wrapping instance.
axiosCookieJarSupport(instance);
instance.defaults.jar = new tough.CookieJar();


const { get, post } = instance;
```
The code fails here:

https://github.com/3846masa/axios-cookiejar-support/blob/master/workspaces/axios-cookiejar-support/lib/index.mjs#L59

In the packaged lib its L73 in /lib/index.js:

![Screen Shot 2019-07-01 at 11 28 48](https://user-images.githubusercontent.com/45361199/60425702-6081fa80-9bf3-11e9-8264-f96aafc5df38.png)

EDIT:

fixed it by using instance instead of this in the anonymous function:

PR: https://github.com/3846masa/axios-cookiejar-support/pull/190

**Comment by 3846masa** [comment]
I think, `const { get } = instance;` syntax will separate instance and function, so `this` will be changed.
axios was not supported this syntax **officially**, so I will not support this syntax.

**Comment by akirilyuk** [comment]
@3846masa nope, this is not working in the even if I am using instance.get and instance.post ...

**Comment by akirilyuk** [comment]
@3846masa OK worked for me, thx

**Comment by akirilyuk** [comment]
@3846masa I have added a PR, which would add support for this. Every test passes. Can you then support it?

**Comment by 3846masa** [comment]
The code you edited is based on axios source code.

https://github.com/axios/axios/blob/8d0b92b2678d96770304dd767cd05a59d37f12cf/lib/core/Axios.js#L64-L84

I decide to keep axios code because I don't know the impact of this change.

If you want to use a short function name, please create a wrap function.

```js
const get = (...args) => axios.get(...args);
```

**Comment by akirilyuk** [comment]
As you can see, in the Axios implementation this is referring to the Axios class. In you code this is referring to the anonymous function.

**Comment by akirilyuk** [comment]
Anyway, the whole concept of destructing single functions is working with pure Axios. If you don't want to support this, then please close this thread.

**Comment by 3846masa** [comment]
First, this two codes have same behavior, so my code hasn't to modify for using normally.
(See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain for more details)

```js
function Test {
}
Test.prototype.get = function () {
  console.log(this);
}
const test = new Test();
test.get();
```

```js
function Test {
}
const test = new Test();
test.get = function () {
  console.log(this);
}
test.get();
```

However, axios will bind this to own prototype when creating instance.
https://github.com/axios/axios/blob/v0.19.0/lib/axios.js#L15-L26

Because of that, you can apply destructuring assignment to axios methods in current version.

I know it, but this behavior isn't basic prototype behavior, so I decide I won't support destructuring assignment.

---

FYI:
If you want to use destructuring assignment, you can write wrapper code to bind this as below.

```js
import _axiosCookieJarSupport from 'axios-cookiejar-support';

function bind(instance) {
  Object.getOwnPropertyNames(instance).forEach((key) => {
    if (typeof instance[key] === 'function') {
      instance[key] = instance[key].bind(instance);
    }
  });
}

export function axiosCookieJarSupport(instance) {
  _axiosCookieJarSupport(instance);
  bind(instance);

  if (instance.create) {
    const create = instance.create;
    instance.create = function() {
      return bind(create.apply(this, arguments));
    };
  }

  return instance;
}
```

```js
import axios from 'axios';
import { axiosCookieJarSupport } from './axios-cookiejar-support';

axiosCookieJarSupport(axios);

const { get } = axios;

get('/').then(console.log);
```

**Comment by akirilyuk** [comment]
Thank you very much for this detailed answer!
