### ISSUE TITLE
Error: in dependency http-cookie-agent@^4

### ISSUE THREAD

**Issue by colinroemer** [3846masa/axios-cookiejar-support#493]
## Describe the bug
On import axios-cookiejar-support throw error no such file or directory on import http-cookie-agent

![image](https://user-images.githubusercontent.com/11738607/168927900-cba42ffe-1951-414a-8175-ae63bb27b0ef.png)

## To Reproduce

1.  install axios-cookiejar-support@^4.0.1
2. export { wrapper } from 'axios-cookiejar-support'
3. create an AxiosIntance with wrapper

## Environments

- OS: Mac Monterey Version 12.3.1
- Node.js version: 14.19.3
- axios version: ^0.27.2
- tough-cookie version: ^4.0.0

**Comment by 3846masa** [comment]
@colinroemer 

Thanks for reporting.

The `node:` schema has been supported since v14.18.0 according to the Node.js documentation, and I believe it will work with the reported Node.js version.

Ref. https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_node_imports

I have actually written reproduction code and it seems to work fine.
The reproduced code can be found at the following URL.

https://gist.github.com/3846masa/b19fa1f313a1780eb33722d5db92efea

I would like you to check once again that the version of Node.js is correct.
